import { Links } from '../components/links';

export const metadata = {
	description: 'Generated by Next.js',
	title: 'Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				{children}
				<Links />
			</body>
		</html>
	);
}
